### ISSUE TITLE
Wrap kendo-grid in an custom directive

### ISSUE THREAD

**Issue by rgiosa** [kendo-labs/angular-kendo#306]
I want to create some basic options to reuse and i think that create a custom directive to wrap a kendo-grid is the way to go.

My custom directive has to offer a new checkbox column to select one row or all rows.

I already have some methods to manipulating selected rows, but my intention is to make this methods a part of directive.

Is this possible?

**Comment by lnghiem** [comment]
@mishoo: Your directive from http://plnkr.co/edit/uq62XqadunzBKJOrR9uT?p=preview is what I was looking for.  However, I noticed that the directive have "scope:true", which make it inherits from the parent scope per my understanding.  As a result, when I tried to use this directive more than once (in my case i used two times since I have two kendo grid on my view from) in the same controller it doesn't work.  Somehow it created two columns/sets of the checkboxes.  I tried to change the "scope: true" to "scope: {}", but it didn't work.  I forked your directive into my plunker and attempted to create an insolated scope by changing it to "scope: { mygridoptions: "="}" and pass in "my gridoptions" attribute.   It works to the point that it has the checkboxes, but it couldn't invoke the selectAll function.  Do you have any suggestions on how to update your directive to use isolated scope so I can use that directive more than once in the same controller?
